Document upgrade workflow
Nordix/metal3-docs pull request #2
Opened 2020-03-13 07:12 UTC by Xenwar

2020-03-13 07:28 UTC, kashifest commented on docs/upgrade-workflow.md
> + please do create a pull request by with content in the relevant sections or a
remove 'by'

2020-03-13 07:57 UTC, Xenwar commented on docs/upgrade-workflow.md
> + please do create a pull request by with content in the relevant sections or a
done

2020-03-13 10:34 UTC, Jaakko-Os requested changes

2020-03-13 10:34 UTC, Jaakko-Os commented on docs/upgrade-workflow.md
> +list could grow or shrink overtime as we learn more about the process.
'grow or shrink'
more technical would be 
'increase or decrease'

2020-03-13 10:34 UTC, Jaakko-Os commented on docs/upgrade-workflow.md
> +- Upgrade of kubernetes binaries, kubeadm, kubelet and kubectl
I don't see the difference between these two cases:
- Upgrade of kubernetes version
- Upgrade of kubernetes binaries, kubeadm, kubelet and kubectl

2020-03-13 10:34 UTC, Jaakko-Os commented on docs/upgrade-workflow.md
> +- Upgrade of boot disk image
what does this mean exactly?

2020-03-13 10:34 UTC, Jaakko-Os commented on docs/upgrade-workflow.md
> +- Repeat relevant experiments from the above list using worker nodes
would be good to mark the 'relevant experiments' somehow

2020-04-02 04:37 UTC, Jaakko-Os commented on docs/upgrade-workflow.md
> +- Upgrade of kubernetes binaries, kubeadm, kubelet and kubectl
There's open PR that tackles this. Two different variables instead of one.
https://github.com/metal3-io/metal3-dev-env/pull/273

2020-04-02 07:47 UTC, Jaakko-Os commented on docs/upgrade-workflow.md
> +  - Upgrade of masters with no extra server
possible when https://github.com/kubernetes-sigs/cluster-api/pull/2688 is merged

2022-02-04 10:30 UTC, Xenwar commented
This PR is outdated as the upgrade workflow is already automated and well documented.

2022-02-04 10:30 UTC, closed without merging